
<?php

//create a variable for the g-recaptcha-response field generated by the API
$response_string = $_POST["g-recaptcha-response"];

//assign const SECRET_KEY to local variable
$secret_key = SECRET_KEY;

//assumed URL for API call
$capchaAPICcall = "https://www.google.com/recaptcha/api/siteverify?secret=$secret_key&response=$response_string";

//get the response data from google
$data = file_get_contents($capchaAPICcall);

//process the JSON into a PHP array
$result = json_decode($data, true);

//Create an IF statement to test the success
if ($result['success'] != 1)
	{
    	//placeholder to handle failiure
        header("Location: error.php");
        die();
    } else {
        //call was succsessful sor process posted data


    	echo "<h2>Thank you</h2>";
    	echo "<p>Thank you for taking the time to complete our survey. Your response was successfully received.</p>";

    	echo "<pre>";
    	echo "NOTE: Included for developement purposes only, the following is a representation of the data submited.";
        print_r($_POST);
        echo "</pre>";
    }
